[package]
name = "esp-flashloader"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# panic-never  = "0.1.0"
riscv = { version = "0.6.0", optional = true }

[dependencies.riscv-rt]
optional = true
version = "0.8.0"
git = "https://github.com/MabezDev/riscv-rt"
rev = "6b55e4aa3895924e31bcd151f2f0ab840836fa07"

[features]
default = []
standalone = ["riscv", "riscv-rt"]

