[package]
name = "esp-flashloader"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
panic-never  = "0.1.0"
ufmt = { version = "0.1.0", optional = true }


[features]
log = ["ufmt"]